"""
PDF Generator — generates bank-grade PDF reports using ReportLab.
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from backend.config.settings import Config


class PdfGenerator:
    """Generates professional bank-grade PDF reports."""

    def __init__(self):
        os.makedirs(Config.REPORTS_DIR, exist_ok=True)

    def generate(self, report_plan: dict, dataframe, insights: str,
                 user_context: dict, output_filename: str) -> str:
        """
        Generate a PDF report and return the absolute file path.
        """
        filepath = os.path.join(Config.REPORTS_DIR, output_filename)
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        elements = []
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'BankTitle', parent=styles['Title'],
            fontSize=24, textColor=colors.HexColor("#0F2B46"), spaceAfter=20,
        )
        heading_style = ParagraphStyle(
            'BankHeading', parent=styles['Heading2'],
            textColor=colors.HexColor("#0F2B46"), spaceBefore=15, spaceAfter=10,
        )
        normal_style = styles['Normal']
        confidential_style = ParagraphStyle(
            'Confidential', parent=normal_style,
            textColor=colors.red, alignment=1, fontSize=10,
        )
        footer_style = ParagraphStyle(
            'Footer', parent=normal_style,
            fontSize=8, textColor=colors.gray, alignment=1,
        )

        # 1. Header
        elements.append(Paragraph("Enterprise Bank Corp.", title_style))
        elements.append(Paragraph("CONFIDENTIAL REPORT", confidential_style))
        elements.append(Spacer(1, 0.2 * inch))

        # 2. Report metadata
        report_title = report_plan.get("report_title", "General Report")
        elements.append(Paragraph(f"Report: {report_title}", heading_style))

        user_name = user_context.get("full_name", user_context.get("username", "Unknown"))
        roles = user_context.get("roles", [])
        role_str = ", ".join(roles) if isinstance(roles, list) else str(roles)
        elements.append(Paragraph(f"Generated By: {user_name} ({role_str})", normal_style))
        elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
        elements.append(Spacer(1, 0.2 * inch))

        # 3. Executive Summary & Insights
        elements.append(Paragraph("1. Executive Summary", heading_style))
        intent = report_plan.get("query_intent", report_plan.get("intent", "N/A"))
        elements.append(Paragraph(f"<b>Intent:</b> {intent}", normal_style))
        elements.append(Spacer(1, 0.1 * inch))

        # Process insights — handle markdown bullet points
        for line in insights.split("\n"):
            line = line.strip()
            if line:
                # Convert markdown bold to HTML bold
                line = line.replace("**", "<b>", 1).replace("**", "</b>", 1)
                elements.append(Paragraph(line, normal_style))
        elements.append(Spacer(1, 0.2 * inch))

        # 4. Data Table
        elements.append(Paragraph("2. Data Evidence", heading_style))

        if dataframe.empty:
            elements.append(Paragraph("No data records found matching criteria.", normal_style))
        else:
            max_rows = 40
            data = []

            # Headers
            headers = [str(col) for col in dataframe.columns]
            data.append(headers)

            # Rows
            for _, row in dataframe.head(max_rows).iterrows():
                data.append([str(val) if val is not None else "—" for val in row])

            # Build table with styling
            table = Table(data, repeatRows=1)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F2B46")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#F8F9FA")),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#DEE2E6")),
                ('FONTSIZE', (0, 0), (-1, -1), 7),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F9FA")]),
            ]))
            elements.append(table)

            if len(dataframe) > max_rows:
                elements.append(Paragraph(
                    f"<i>... {len(dataframe) - max_rows} additional rows truncated.</i>",
                    normal_style,
                ))

        # 5. Footer
        elements.append(Spacer(1, 0.5 * inch))
        elements.append(Paragraph("INTERNAL USE ONLY — NOT FOR DISTRIBUTION", footer_style))

        doc.build(elements)
        return filepath
