"""
PDF Generator — generates bank-grade PDF reports using ReportLab.

Header: "AVANZA Solutions" followed by the report title, summarized
insights, and then the data evidence table.
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)
from reportlab.lib.units import inch
from backend.config.settings import Config


class PdfGenerator:
    """Generates professional bank-grade PDF reports."""

    def __init__(self):
        os.makedirs(Config.REPORTS_DIR, exist_ok=True)

    def generate(self, report_plan: dict, dataframe, insights: str,
                 user_context: dict, output_filename: str) -> str:
        """
        Generate a PDF report and return the absolute file path.
        """
        filepath = os.path.join(Config.REPORTS_DIR, output_filename)
        doc = SimpleDocTemplate(
            filepath, pagesize=letter,
            topMargin=0.6 * inch, bottomMargin=0.6 * inch,
            leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        )
        elements = []
        styles = getSampleStyleSheet()

        # ── Custom Styles ─────────────────────────────────────────
        company_style = ParagraphStyle(
            'CompanyHeader', parent=styles['Title'],
            fontSize=28, textColor=colors.HexColor("#B51568"),
            spaceAfter=4, alignment=1,
        )
        report_title_style = ParagraphStyle(
            'ReportTitle', parent=styles['Heading1'],
            fontSize=20, textColor=colors.HexColor("#0F2B46"),
            spaceBefore=10, spaceAfter=6, alignment=1,
        )
        heading_style = ParagraphStyle(
            'BankHeading', parent=styles['Heading2'],
            textColor=colors.HexColor("#0F2B46"),
            spaceBefore=15, spaceAfter=10,
        )
        normal_style = styles['Normal']
        meta_style = ParagraphStyle(
            'MetaInfo', parent=normal_style,
            fontSize=9, textColor=colors.HexColor("#555555"),
            alignment=1,
        )
        confidential_style = ParagraphStyle(
            'Confidential', parent=normal_style,
            textColor=colors.red, alignment=1, fontSize=10,
        )
        footer_style = ParagraphStyle(
            'Footer', parent=normal_style,
            fontSize=8, textColor=colors.gray, alignment=1,
        )

        # ══════════════════════════════════════════════════════════
        # 1. Company Header — "AVANZA Solutions"
        # ══════════════════════════════════════════════════════════
        elements.append(Paragraph("AVANZA Solutions", company_style))
        elements.append(HRFlowable(
            width="100%", thickness=2,
            color=colors.HexColor("#B51568"), spaceBefore=2, spaceAfter=8,
        ))
        elements.append(Paragraph("CONFIDENTIAL", confidential_style))
        elements.append(Spacer(1, 0.15 * inch))

        # ══════════════════════════════════════════════════════════
        # 2. Report Title & Metadata
        # ══════════════════════════════════════════════════════════
        report_title = report_plan.get("report_title", "General Report")
        elements.append(Paragraph(report_title, report_title_style))

        user_name = user_context.get("full_name", user_context.get("username", "Unknown"))
        roles = user_context.get("roles", [])
        role_str = ", ".join(roles) if isinstance(roles, list) else str(roles)
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        elements.append(Paragraph(
            f"Generated by: {user_name} ({role_str}) &nbsp;|&nbsp; Date: {generated_at}",
            meta_style,
        ))
        elements.append(Spacer(1, 0.2 * inch))

        # ══════════════════════════════════════════════════════════
        # 3. Data Evidence Table
        # ══════════════════════════════════════════════════════════
        elements.append(Paragraph("Data Evidence", heading_style))

        if dataframe.empty:
            elements.append(Paragraph(
                "No data records found matching criteria.", normal_style
            ))
        else:
            max_rows = 40
            data = []

            # Headers
            headers = [str(col) for col in dataframe.columns]
            data.append(headers)

            # Rows
            for _, row in dataframe.head(max_rows).iterrows():
                data.append([str(val) if val is not None else "—" for val in row])

            # Build table with styling
            table = Table(data, repeatRows=1)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#B51568")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#F8F9FA")),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#DEE2E6")),
                ('FONTSIZE', (0, 0), (-1, -1), 7),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1),
                 [colors.white, colors.HexColor("#F8F9FA")]),
            ]))
            elements.append(table)

            if len(dataframe) > max_rows:
                elements.append(Paragraph(
                    f"<i>... {len(dataframe) - max_rows} additional rows truncated.</i>",
                    normal_style,
                ))

        # ══════════════════════════════════════════════════════════
        # 6. Footer
        # ══════════════════════════════════════════════════════════
        elements.append(Spacer(1, 0.5 * inch))
        elements.append(HRFlowable(
            width="100%", thickness=1,
            color=colors.HexColor("#DEE2E6"), spaceBefore=4, spaceAfter=6,
        ))
        elements.append(Paragraph(
            "AVANZA Solutions — INTERNAL USE ONLY — NOT FOR DISTRIBUTION",
            footer_style,
        ))

        doc.build(elements)
        return filepath
